version: '3.0'

expectations:
  population_size: 10000
   
actions:

  generate_delivery_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_delivery --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_delivery.csv.gz

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/population_characteristics.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400

    needs: [generate_delivery_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/population_characteristics.html 
        figures: interim-outputs/figures/*
        tables: interim-outputs/tables/*
        csvs: machine_readable_outputs/*/* # two possible subfolders
        text: interim-outputs/text/*
        
  generate_simple_report:
    run: jupyter:latest env IMAGE_FORMAT=png jupyter nbconvert /workspace/notebooks/opensafely_vaccine_report_overall.ipynb --execute --to html --template basic --output=/workspace/output/opensafely_vaccine_report_overall_simple.html --ExecutePreprocessor.timeout=86400 --no-input

    needs: [generate_delivery_cohort, generate_notebook]
    outputs:
      moderately_sensitive:
        notebook: output/opensafely_vaccine_report_overall_simple.html
        csvs: machine_readable_outputs/table_csvs/*