version: '3.0'

expectations:
  population_size: 10000
    
actions:

  generate_delivery_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_delivery --output-format=csv.gz

    outputs:
      highly_sensitive:
        cohort: output/input_delivery.csv.gz
  
  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/population_characteristics.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --debug

    needs: [generate_delivery_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/population_characteristics.html 
        figures: interim-outputs/figures/*
        tables: interim-outputs/tables/*
        fig_csvs_1: output/machine_readable_outputs/figure_csvs/*ethnicity*.csv 
        fig_csvs_2: output/machine_readable_outputs/figure_csvs/*imd*.csv 
        fig_csvs_3: output/machine_readable_outputs/figure_csvs/*psychosis*.csv 
        fig_csvs_4: output/machine_readable_outputs/figure_csvs/*LD_*.csv 
        fig_csvs_5: output/machine_readable_outputs/figure_csvs/*eligible*.csv 
        text: interim-outputs/text/*
        
        
  generate_simple_report:
    run: jupyter:latest env IMAGE_FORMAT=png jupyter nbconvert /workspace/notebooks/opensafely_vaccine_report_overall.ipynb --execute --to html --template basic --output=/workspace/output/opensafely_vaccine_report_overall_simple.html --ExecutePreprocessor.timeout=86400 --no-input

    needs: [generate_delivery_cohort, generate_notebook]
    outputs:
      moderately_sensitive:
        notebook: output/opensafely_vaccine_report_overall_simple.html
        csvs: output/machine_readable_outputs/table_csvs/*

        
  generate_report_second_doses:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/second_doses.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input

    needs: [generate_notebook]
    outputs:
      moderately_sensitive:
        notebook: output/second_doses.html
        tables: output/machine_readable_outputs/second_doses/*.csv
       
  generate_report_third_doses:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/booster-third-doses.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input

    needs: [generate_notebook]
    outputs:
      moderately_sensitive:
        notebook: output/booster-third-doses.html
        tables: output/machine_readable_outputs/third_doses/*.csv
       
